'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(__dirname,'../ingemar-preview.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/);
const familyHtml=fs.readFileSync(path.join(root,'ingemar-session/exercise.html'),'utf8');
const productionHtml=fs.readFileSync(path.join(root,'exercise.html'),'utf8');
function sessionMarkup(text){const start=text.indexOf('<!-- ── SESSION MODE ── -->'),end=text.indexOf('<datalist id="type-suggestions"',start);assert.ok(start>=0&&end>start,'Session markup bounds missing');return text.slice(start,end).trim();}
test('standalone preview has valid inline JavaScript and does not load Firebase',()=>{
 assert.ok(source,'Preview script missing');
 new vm.Script(source[1],{filename:'ingemar-preview.html'});
 assert.doesNotMatch(html,/firebase-app-compat|firebase-sync\.js|auth-gate\.js|firebase\.database/);
 assert.match(html,/<title>Ingemars träning · Förhandsvisning<\/title>/);
 assert.match(html,/ingemar-pulse-demo-v1/);
});
test('workout builder provides independently editable set weights, reps and minutes',()=>{
 assert.match(source[1],/e\.sets\.map\(function\(s,j\)/);
 assert.match(html,/#builder\{width:min\(660px,calc\(100dvw - 20px\)\);max-width:calc\(100dvw - 20px\);max-height:calc\(100dvh - 20px\);overflow-x:hidden;overflow-y:auto/);
 assert.match(html,/@media\(max-width:600px\)\{\s*#builder \.modal-head/);
 assert.match(html,/#builder \.exercise-fields\{grid-template-columns:minmax\(0,1fr\)/);
 assert.match(html,/class="builder-date-control"/);
 assert.match(html,/id="build-date-text" class="builder-date-text"/);
 assert.match(html,/#builder \.builder-date-control\{position:relative;display:flex;align-items:center;justify-content:center;width:100%/);
 assert.match(html,/#builder #build-date\{position:absolute;inset:0;display:block;width:100%;height:100%/);
 assert.match(source[1],/function builderDateText\(iso\)/);
 assert.doesNotMatch(html,/::-webkit-date-and-time-value|::-webkit-datetime-edit/);
 assert.doesNotMatch(html,/#builder \.field\{display:grid/);
 assert.match(html,/#builder \.modal-actions \.right\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
 assert.doesNotMatch(html,/Builder-only small-screen layout/);
 assert.match(source[1],/data-set=/);
 assert.match(source[1],/data-mode=/);
 assert.match(source[1],/data-add-set=/);
 assert.match(source[1],/data-remove-set=/);
 assert.match(source[1],/weight:weight\|\|0,reps:reps\|\|0,minutes:minutes\|\|0/);
 assert.match(source[1],/function exerciseCatalogSources\(\)/);
 assert.match(source[1],/state\.history\.slice\(\)/);
 assert.match(source[1],/Object\.keys\(state\.plans\)/);
 assert.match(source[1],/function exerciseNameCatalog\(type,mode\)/);
 assert.match(html,/id="builder-template-select"/);
 assert.match(html,/data-action="save-template">Spara som mall/);
 assert.match(html,/data-copy-exercise="/);
 assert.match(html,/data-drag-exercise="/);
 for(const fn of ['builderTemplates','saveBuilderTemplate','applyBuilderTemplate','deleteBuilderTemplate','copyDraftExercise','moveDraftExercise','startBuilderDrag','moveBuilderDrag','endBuilderDrag'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/templates:\[\]/);
 assert.match(source[1],/if\(!Array\.isArray\(value\.templates\)\)value\.templates=\[\]/);
 assert.match(html,/#builder \.builder-row-drag\{[^}]*touch-action:none/);
 assert.match(html,/\.builder-drag-ghost\{position:fixed!important/);
 assert.match(source[1],/localeCompare\(b\.name,'sv-SE',\{sensitivity:'base'\}\)/);
 assert.match(source[1],/>＋ Ny övning<\/button>/);
 assert.match(source[1],/data-exercise-name-free="1"/);
 assert.doesNotMatch(source[1],/exerciseNames|exerciseCatalogRegistry|localStorage\.setItem\([^\n]*exercise/i);
 assert.match(html,/body\[data-builder-open="true"\]\{position:fixed/);
 assert.match(html,/#builder::backdrop\{background:#020409ed;backdrop-filter:none;-webkit-backdrop-filter:none\}/);
 assert.match(source[1],/function lockBuilderBackground\(\)/);
 assert.match(source[1],/function unlockBuilderBackground\(\)/);
 assert.match(html,/data-action="plan-week">Planera vecka ↗/);
 assert.match(html,/id="week-planner"/);
 assert.match(html,/id="week-template-select"/);
 assert.match(html,/data-action="save-week">Spara hela veckan ✓/);
 assert.match(html,/data-action="save-week-template">Spara veckan som mall/);
 for(const fn of ['seedWeekTemplates','weekDraftFromMonday','openWeekPlanner','renderWeekPlanner','setWeekDayType','toggleWeekExercise','applyWeekDayTemplate','weekPlannerSummaryText','copyWeekDay','swapWeekDays','saveWholeWeek','saveWeekTemplate','applyWeekTemplate','deleteWeekTemplate','startWeekDrag','moveWeekDrag','endWeekDrag'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/weekTemplates:seedWeekTemplates\(\)/);
 assert.match(source[1],/if\(!Array\.isArray\(value\.weekTemplates\)\)value\.weekTemplates=seedWeekTemplates\(\)/);
 assert.match(source[1],/state\.plans\[date\]=weekPlanClone\(entry\)/);
 assert.match(source[1],/delete state\.plans\[date\]/);
 assert.match(source[1],/weekDraft\[to\]=weekPlanClone\(weekDraft\[from\]\)/);
 assert.match(html,/#week-planner\{width:min\(780px,calc\(100dvw - 20px\)\)/);
 assert.match(html,/\.week-planner-drag\{[^}]*touch-action:none/);
 for(const fn of ['openWeekDayBuilder','restoreWeekPlannerFromBuilder','weekExercisePreset','weekExerciseChoices','positionWeekDrag','glowBarsMarkup','selectGlowBar','chartAxisDisplay','chartSeriesColor','inspectChartPoint','installChartPointHandlers'])assert.ok(source[1].includes('function '+fn+'('),fn);
 for(const control of ['data-week-edit','data-week-type','data-week-exercise','data-week-toggle-day','data-week-copy-target','data-chart-point','data-chart-bar'])assert.match(source[1],new RegExp(control),control);
 assert.doesNotMatch(source[1],/function setWeekDaySource|data-week-source|data-week-add-exercise|data-week-remove-exercise|data-week-toggle-exercises/);
 assert.match(html,/class="week-planner-guide"/);
 assert.match(html,/id="week-planner-summary"/);
 for(const id of ['bars-inspect','zen-bars-inspect','pp-volume-chart-inspect','pp-exercise-chart-inspect'])assert.match(html,new RegExp('id="'+id+'"'),id);
 assert.match(source[1],/if\(builderWeekIndex>=0\)\{weekDraft\[builderWeekIndex\]=weekPlanClone\(draft\)/);
 assert.match(source[1],/document\.removeEventListener\('pointermove',moveWeekDrag\)/);
 assert.match(source[1],/Math\.min\(window\.innerWidth-w-8/);
 assert.doesNotMatch(source[1],/var pointWidth=g\.innerW\/count/);
});
test('preview includes an isolated training log and interactive Zen modes',()=>{
 assert.match(html,/class="zen-flow-visual training-flow-visual"/);
 assert.match(html,/id="training-flow-gradient"/);
 assert.match(html,/id="training-flow-glow"/);
 assert.match(html,/class="zen-flow-trace"[^>]*stroke="url\(#training-flow-gradient\)"/);
 assert.match(html,/id="orbit-kind"/);
 assert.match(html,/id="orbit-summary"/);
 assert.doesNotMatch(html,/class="orbit"|class="orbit-inner"|class="orbit-dot"/);
 assert.match(fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8'),/\.training-flow-visual\{[\s\S]*?--zen-accent:#ff4f6d/);
 assert.match(fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8'),/@keyframes zenFlowSweep/);
 assert.match(fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8'),/\.training-flow-visual\{max-width:100%;margin:4px 0 0\}/);
 for(const route of ['training','stretch','meditation'])assert.match(html,new RegExp('data-view="'+route+'"'));
 for(const type of ['Push','Pull','Kondition'])assert.match(html,new RegExp('data-choice="'+type+'"'));
 assert.match(source[1],/zenHistory/);
 assert.match(source[1],/activeZen/);
 assert.match(source[1],/state\.history\.push\(event\.data\.workout\)/);
 assert.match(html,/id="history-detail"/);
 assert.match(source[1],/function openHistory\(id\)/);
 assert.match(source[1],/localStorage\.setItem\(KEY/);
 assert.match(source[1],/Återställa all demodata/);
});

test('Ingemar training delegates to the exact Markus/Maja family session',()=>{
 assert.match(html,/id="family-session-frame"[^>]*src="ingemar-session\/exercise\.html\?user=ingemar"/);
 assert.doesNotMatch(html,/id="session-modal"|id="session-live-timer"|ingemar-pulse-original\.css/);
 assert.equal(sessionMarkup(familyHtml),sessionMarkup(productionHtml),'Family host must use the exact production session modal markup');
 const productionStyle=(productionHtml.match(/<style>([\s\S]*?)<\/style>/)||[])[1],familyStyle=(familyHtml.match(/<style data-family-base>([\s\S]*?)<\/style>/)||[])[1];
 assert.equal(familyStyle,productionStyle,'Family host base CSS must be byte-for-byte identical to production');
 const requiredAssets=['exercise-timer-focus.js','exercise-session-enhancements.js','exercise-session-runtime-core-v21.js','exercise-session-theme-stability.js','exercise-session-stable-details.js','exercise-between-routing-v7.js','exercise-between-custom-exercise-v3.js','exercise-between-sets.js','exercise-hype-polish.js','exercise-flow-polish-v2.js','exercise-session-set-cards-v6.js','exercise-session-shell-v19.js','exercise-session-ux-v20.js','exercise-motion-v1.js','exercise-hype-timer-layout-v1.js','exercise-session-stability-v55.js','exercise-custom-transition-atomic-v56.js','exercise-pulse-flow-v58.js','exercise-pulse-flow-motion-v67.js','exercise-session-typography.js','exercise-pulse-flow-progress-marker-v92.js','exercise-pulse-flow-completed-marker-v102.js','exercise-pulse-flow-ecg-glow-v104.js','exercise-pulse-flow-canvas-glow-v130.js','exercise-pulse-flow-canvas-glow-v131.js','exercise-session-transition-stability-v142.js','exercise-session-persistence-v143.js'];
 requiredAssets.forEach(asset=>assert.ok(familyHtml.includes('src="'+asset+'?v='),asset));
 assert.doesNotMatch(familyHtml,/firebase-app-compat|firebase-auth-compat|firebase-database-compat|firebase-sync\.js|auth-gate\.js|auth-config\.js/);
 assert.match(source[1],/function sendFamilySession\(\)/);assert.match(source[1],/ingemar-family-session-saved/);
 assert.match(familyHtml,/function sessionToIngemarWorkout\(\)/);
 assert.match(familyHtml,/actualWeight/);assert.match(familyHtml,/actualReps/);
 assert.match(familyHtml,/done:true,skipped:false/);
 assert.match(familyHtml,/parent\.postMessage\(\{type:'ingemar-family-session-saved'/);
 assert.doesNotMatch(source[1],/function renderSession\(|function startCurrentSet\(|function paintSessionRing\(/);
 Array.from(familyHtml.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)).map(m=>m[1]).filter(Boolean).forEach((script,index)=>new vm.Script(script,{filename:'ingemar-family-session-inline-'+index+'.js'}));
});

test('push/pull analytics track load, balance and exercise progression from demo history',()=>{
 const css=fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8');
 for(const id of ['pp-volume-chart','pp-push-volume','pp-pull-volume','pp-balance','pp-set-count','pp-rep-count','pp-exercise-chart','pp-exercise-pills'])assert.match(html,new RegExp('id="'+id+'"'));
 for(const metric of ['volume','weight','e1rm'])assert.match(html,new RegExp('data-analytics-metric="'+metric+'"'));
 for(const type of ['Push','Pull'])assert.match(html,new RegExp('data-analytics-type="'+type+'"'));
 for(const fn of ['strengthDemoHistory','hydrateStrengthDemo','strengthWeeks','strengthMetric','comparisonChartSvg','analyticsCounterExercise','renderPushPullAnalytics'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/Bänkpress/);
 assert.match(source[1],/Latsdrag/);
 assert.match(source[1],/Bänkpress':'Sittande rodd/);
 assert.match(source[1],/Axelpress':'Latsdrag/);
 assert.match(source[1],/Tricepspress':'Hantelcurl/);
 assert.match(source[1],/detailSeries\.push\(/);
 assert.match(html,/id="pp-exercise-compare"/);
 assert.match(source[1],/w\*\(1\+r\/30\)/);
 assert.match(source[1],/renderPushPullAnalytics\(\)/);
 assert.match(css,/\/\* INGEMAR PUSH PULL ANALYTICS/);
 assert.match(css,/\.pp-line\.push\{/);
 assert.match(css,/\.pp-line\.pull\{/);
 assert.match(css,/\.pp-line\.primary\{/);
 assert.match(css,/\.pp-line\.comparison\{/);
 assert.match(css,/\.pp-area\{/);
 assert.match(css,/\.pp-selector-halo/);
 assert.match(css,/\.pp-chart-shell/);
 assert.match(source[1],/linearGradient id=/);
 assert.match(source[1],/class="pp-y-label"/);
 assert.match(source[1],/class="zen-style-bar-fill/);
 assert.match(css,/@media\(max-width:390px\)/);
});

test('shared family iframe and Zen remain mobile friendly',()=>{
 const css=fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8');
 assert.match(html,/ingemar-preview-modes\.css\?v=20260922-family-session-13/);
 assert.match(css,/\.family-session-frame\{position:fixed;inset:0;z-index:55/);
 assert.match(css,/\.mode-screen\{[\s\S]*overflow-x:hidden/);assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/@media\(max-width:360px\)/);assert.match(css,/env\(safe-area-inset-bottom\)/);
 assert.match(html,/<section id="zen-session" class="mode-screen zen-workout"/);assert.match(source[1],/function nextZen\(\)/);assert.match(source[1],/function selectZenStep\(index\)/);
 for(const id of ['zen-step-arc','zen-step-marker','zen-total-time','zen-next-step','zen-next-meta','zen-breath-pulse'])assert.match(html,new RegExp('id="'+id+'"'));
 assert.match(html,/id="zen-step-arc"[^>]*stroke-dashoffset="100"/);assert.doesNotMatch(css,/\.zen-workout \.zen-step-arc\{[^}]*stroke-dashoffset:100/);
 assert.match(html,/id="zen-total-progress" role="progressbar"/);assert.match(css,/\.zen-workout \.zen-step-arc\{/);assert.match(css,/\.zen-workout \.zen-total-time\{/);
 assert.match(source[1],/arc\.setAttribute\('stroke-dashoffset'/);assert.match(source[1],/zen-total-progress'\)\.setAttribute\('aria-valuenow'/);
 assert.match(source[1],/function startZenTimer\(\)/);assert.match(source[1],/function stopZenTimer\(\)/);assert.match(source[1],/function zenAnimationTick\(\)/);assert.match(source[1],/requestAnimationFrame\(zenAnimationTick\)/);assert.match(source[1],/cancelAnimationFrame\(zenAnimationFrame\)/);
 assert.match(source[1],/function zenAnimationFallback\(\)/);assert.match(source[1],/setInterval\(zenAnimationFallback,64\)/);assert.match(source[1],/clearInterval\(zenAnimationWatchdog\)/);
 assert.doesNotMatch(source[1],/if\(!document\.hidden\)zenTick/);assert.match(source[1],/zenTick\(Date\.now\(\)\)/);
 assert.doesNotMatch(source[1],/zenTimer=setInterval|setInterval\(function\(\)\{[\s\S]*?zenTick/);assert.match(source[1],/med\?'STEG KVAR':'RÖRELSE KVAR'/);assert.match(css,/--mode-glow:/);
 assert.match(css,/\.zen-workout \.zen-step-arc\{[^}]*filter:[^}]*drop-shadow\(0 0 \d+px var\(--mode-accent\)\)/);assert.match(css,/\.zen-clock-inner\{[^\n]*width:72%;max-width:72%/);assert.match(html,/class="zen-focus-grid"/);assert.match(css,/\.zen-focus-card,\.zen-journey-card\{/);assert.match(css,/@keyframes zenWaterRipple/);
 assert.doesNotMatch(css,/stroke-dashoffset \.38s/);assert.doesNotMatch(css,/\.zen-clock-wrap\.is-switching/);assert.doesNotMatch(html,/firebase-app-compat|firebase-sync\.js|auth-gate\.js/);
});
