'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(__dirname,'../ingemar-preview.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/);
test('standalone preview has valid inline JavaScript and does not load Firebase',()=>{
 assert.ok(source,'Preview script missing');
 new vm.Script(source[1],{filename:'ingemar-preview.html'});
 assert.doesNotMatch(html,/firebase-app-compat|firebase-sync\.js|auth-gate\.js|firebase\.database/);
 assert.match(html,/<title>Ingemars träning · Förhandsvisning<\/title>/);
 assert.match(html,/ingemar-pulse-demo-v1/);
});
test('workout builder provides independently editable set weights, reps and minutes',()=>{
 assert.match(source[1],/e\.sets\.map\(function\(s,j\)/);
 assert.match(html,/#builder\{width:min\(660px,calc\(100dvw - 20px\)\);max-width:calc\(100dvw - 20px\);max-height:calc\(100dvh - 20px\);overflow-x:hidden;overflow-y:auto/);
 assert.match(html,/@media\(max-width:600px\)\{\s*#builder \.modal-head/);
 assert.match(html,/#builder \.exercise-fields\{grid-template-columns:minmax\(0,1fr\)/);
 assert.match(html,/class="builder-date-control"/);
 assert.match(html,/id="build-date-text" class="builder-date-text"/);
 assert.match(html,/#builder \.builder-date-control\{position:relative;display:flex;align-items:center;justify-content:center;width:100%/);
 assert.match(html,/#builder #build-date\{position:absolute;inset:0;display:block;width:100%;height:100%/);
 assert.match(source[1],/function builderDateText\(iso\)/);
 assert.doesNotMatch(html,/::-webkit-date-and-time-value|::-webkit-datetime-edit/);
 assert.doesNotMatch(html,/#builder \.field\{display:grid/);
 assert.match(html,/#builder \.modal-actions \.right\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
 assert.doesNotMatch(html,/Builder-only small-screen layout/);
 assert.match(source[1],/data-set=/);
 assert.match(source[1],/data-actual=/);
 assert.match(source[1],/data-mode=/);
 assert.match(source[1],/data-add-set=/);
 assert.match(source[1],/data-remove-set=/);
 assert.match(source[1],/weight:weight\|\|0,reps:reps\|\|0,minutes:minutes\|\|0/);
 assert.match(source[1],/exercises:selectedExercises/);
 assert.match(source[1],/set\.done/);
 assert.match(source[1],/function exerciseCatalogSources\(\)/);
 assert.match(source[1],/state\.history\.slice\(\)/);
 assert.match(source[1],/Object\.keys\(state\.plans\)/);
 assert.match(source[1],/function exerciseNameCatalog\(type,mode\)/);
 assert.match(html,/id="builder-template-select"/);
 assert.match(html,/data-action="save-template">Spara som mall/);
 assert.match(html,/data-copy-exercise="/);
 assert.match(html,/data-drag-exercise="/);
 for(const fn of ['builderTemplates','saveBuilderTemplate','applyBuilderTemplate','deleteBuilderTemplate','copyDraftExercise','moveDraftExercise','startBuilderDrag','moveBuilderDrag','endBuilderDrag'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/templates:\[\]/);
 assert.match(source[1],/if\(!Array\.isArray\(value\.templates\)\)value\.templates=\[\]/);
 assert.match(html,/#builder \.builder-row-drag\{[^}]*touch-action:none/);
 assert.match(html,/\.builder-drag-ghost\{position:fixed!important/);
 assert.match(source[1],/localeCompare\(b\.name,'sv-SE',\{sensitivity:'base'\}\)/);
 assert.match(source[1],/>＋ Ny övning<\/button>/);
 assert.match(source[1],/data-exercise-name-free="1"/);
 assert.doesNotMatch(source[1],/exerciseNames|exerciseCatalogRegistry|localStorage\.setItem\([^\n]*exercise/i);
 assert.match(html,/body\[data-builder-open="true"\]\{position:fixed/);
 assert.match(html,/#builder::backdrop\{background:#020409ed;backdrop-filter:none;-webkit-backdrop-filter:none\}/);
 assert.match(source[1],/function lockBuilderBackground\(\)/);
 assert.match(source[1],/function unlockBuilderBackground\(\)/);
 assert.match(html,/data-action="plan-week">Planera vecka ↗/);
 assert.match(html,/id="week-planner"/);
 assert.match(html,/id="week-template-select"/);
 assert.match(html,/data-action="save-week">Spara hela veckan ✓/);
 assert.match(html,/data-action="save-week-template">Spara veckan som mall/);
 for(const fn of ['seedWeekTemplates','weekDraftFromMonday','openWeekPlanner','renderWeekPlanner','setWeekDayType','toggleWeekExercise','applyWeekDayTemplate','weekPlannerSummaryText','copyWeekDay','swapWeekDays','saveWholeWeek','saveWeekTemplate','applyWeekTemplate','deleteWeekTemplate','startWeekDrag','moveWeekDrag','endWeekDrag'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/weekTemplates:seedWeekTemplates\(\)/);
 assert.match(source[1],/if\(!Array\.isArray\(value\.weekTemplates\)\)value\.weekTemplates=seedWeekTemplates\(\)/);
 assert.match(source[1],/state\.plans\[date\]=weekPlanClone\(entry\)/);
 assert.match(source[1],/delete state\.plans\[date\]/);
 assert.match(source[1],/weekDraft\[to\]=weekPlanClone\(weekDraft\[from\]\)/);
 assert.match(html,/#week-planner\{width:min\(780px,calc\(100dvw - 20px\)\)/);
 assert.match(html,/\.week-planner-drag\{touch-action:none/);
 for(const fn of ['openWeekDayBuilder','restoreWeekPlannerFromBuilder','weekExercisePreset','weekExerciseChoices','positionWeekDrag','glowBarsMarkup','selectGlowBar','chartAxisDisplay','chartSeriesColor','inspectChartPoint','installChartPointHandlers'])assert.ok(source[1].includes('function '+fn+'('),fn);
 for(const control of ['data-week-edit','data-week-type','data-week-exercise','data-week-toggle-day','data-week-copy-target','data-chart-point','data-chart-bar'])assert.match(source[1],new RegExp(control),control);
 assert.doesNotMatch(source[1],/function setWeekDaySource|data-week-source|data-week-add-exercise|data-week-remove-exercise|data-week-toggle-exercises/);
 assert.match(html,/class="week-planner-guide"/);
 assert.match(html,/id="week-planner-summary"/);
 for(const id of ['bars-inspect','zen-bars-inspect','pp-volume-chart-inspect','pp-exercise-chart-inspect'])assert.match(html,new RegExp('id="'+id+'"'),id);
 assert.match(source[1],/if\(builderWeekIndex>=0\)\{weekDraft\[builderWeekIndex\]=weekPlanClone\(draft\)/);
 assert.match(source[1],/document\.removeEventListener\('pointermove',moveWeekDrag\)/);
 assert.match(source[1],/Math\.min\(window\.innerWidth-w-8/);
 assert.doesNotMatch(source[1],/var pointWidth=g\.innerW\/count/);
});
test('preview includes an isolated training log and interactive Zen modes',()=>{
 for(const route of ['training','stretch','meditation'])assert.match(html,new RegExp('data-view="'+route+'"'));
 for(const type of ['Push','Pull','Kondition'])assert.match(html,new RegExp('data-choice="'+type+'"'));
 assert.match(source[1],/zenHistory/);
 assert.match(source[1],/activeZen/);
 assert.match(source[1],/state\.history\.push\(workout\)/);
 assert.match(html,/id="history-detail"/);
 assert.match(source[1],/function openHistory\(id\)/);
 assert.match(source[1],/localStorage\.setItem\(KEY/);
 assert.match(source[1],/Återställa all demodata/);
});

test('training mode embeds the original Pulse Flow CSS and ordered set decisions',()=>{
 const original=fs.readFileSync(path.join(root,'exercise-pulse-flow-v58.js'),'utf8');
 const quote=String.fromCharCode(96);
 const body=original.split('style.textContent = '+quote)[1].split(quote+';\n    document.head.appendChild(style)')[0];
 const css=fs.readFileSync(path.join(root,'ingemar-pulse-original.css'),'utf8');
 assert.ok(body.length>25000,'Original stylesheet extraction should be available');
 assert.ok(css.includes(body.trimEnd()),'Demo must contain the original family Pulse Flow CSS without trailing whitespace');
 for(const phrase of ['id="session-modal" class="pulse-flow-v58 pulse-flow-strength-v58 show"',
  'class="session-shell"','class="session-timers"','class="hype-workout-progress"',
  'id="session-stable-details"','id="pulse-flow-live-v58"',
  'class="pulse-flow-trace-v58"','id="session-exercises" tabindex="0"'])assert.ok(html.includes(phrase),phrase);
 for(const fn of ['startCurrentSet','completeCurrentSet','startNextSet','addExtraSet',
  'finishCurrentExercise','skipSessionRest'])assert.ok(source[1].includes('function '+fn+'()'),fn);
 assert.match(source[1],/set\.skipped/);
 assert.match(source[1],/dataset\.state=phase/);
 assert.match(html,/id="session-pre-timer"/);
 assert.match(html,/id="session-prestart-toggle"/);
 assert.match(source[1],/function skipPrestart\(\)/);
 assert.match(source[1],/function togglePrestart\(\)/);
 assert.match(source[1],/active\.preUntil=Date\.now\(\)\+5000/);
 assert.doesNotMatch(html,/<dialog id="session"/);
});
test('push/pull analytics track load, balance and exercise progression from demo history',()=>{
 const css=fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8');
 for(const id of ['pp-volume-chart','pp-push-volume','pp-pull-volume','pp-balance','pp-set-count','pp-rep-count','pp-exercise-chart','pp-exercise-pills'])assert.match(html,new RegExp('id="'+id+'"'));
 for(const metric of ['volume','weight','e1rm'])assert.match(html,new RegExp('data-analytics-metric="'+metric+'"'));
 for(const type of ['Push','Pull'])assert.match(html,new RegExp('data-analytics-type="'+type+'"'));
 for(const fn of ['strengthDemoHistory','hydrateStrengthDemo','strengthWeeks','strengthMetric','comparisonChartSvg','analyticsCounterExercise','renderPushPullAnalytics'])assert.ok(source[1].includes('function '+fn+'('),fn);
 assert.match(source[1],/Bänkpress/);
 assert.match(source[1],/Latsdrag/);
 assert.match(source[1],/Bänkpress':'Sittande rodd/);
 assert.match(source[1],/Axelpress':'Latsdrag/);
 assert.match(source[1],/Tricepspress':'Hantelcurl/);
 assert.match(source[1],/detailSeries\.push\(/);
 assert.match(html,/id="pp-exercise-compare"/);
 assert.match(source[1],/w\*\(1\+r\/30\)/);
 assert.match(source[1],/renderPushPullAnalytics\(\)/);
 assert.match(css,/\/\* INGEMAR PUSH PULL ANALYTICS/);
 assert.match(css,/\.pp-line\.push\{/);
 assert.match(css,/\.pp-line\.pull\{/);
 assert.match(css,/\.pp-line\.primary\{/);
 assert.match(css,/\.pp-line\.comparison\{/);
 assert.match(css,/\.pp-area\{/);
 assert.match(css,/\.pp-selector-halo/);
 assert.match(css,/\.pp-chart-shell/);
 assert.match(source[1],/linearGradient id=/);
 assert.match(source[1],/class="pp-y-label"/);
 assert.match(source[1],/class="zen-style-bar-fill/);
 assert.match(css,/@media\(max-width:390px\)/);
});

test('independent editable set rail and Zen remain mobile friendly',()=>{
 const css=fs.readFileSync(path.join(root,'ingemar-preview-modes.css'),'utf8');
 const pulse=fs.readFileSync(path.join(root,'ingemar-pulse-original.css'),'utf8');
 assert.match(html,/ingemar-preview-modes\.css\?v=20260921-planner-telemetry-8/);
 assert.match(html,/ingemar-pulse-original\.css\?v=20260921-family-structure-1/);
 assert.match(css,/\.mode-screen\{[\s\S]*overflow-x:hidden/);
 assert.match(css,/@media\(max-width:900px\)/);
 assert.match(css,/@media\(max-width:360px\)/);
 assert.match(css,/env\(safe-area-inset-bottom\)/);
 assert.match(pulse,/#session-modal \.session-set-rail\{/);
 assert.match(pulse,/#session-modal \.session-set-rail\{[^\n]*max-height:none;overflow:visible/);
 assert.doesNotMatch(pulse, /max-height:clamp\(175px,31dvh,320px\)/);
 assert.match(pulse,/#session-modal \.pf-live-ring::before/);
 assert.match(pulse,/#session-modal \.pf-arc-progress-v80/);
 assert.match(pulse,/@keyframes ingemarEcgSweep/);
 assert.match(source[1],/function paintSessionRing\(now\)/);
 assert.match(source[1],/requestAnimationFrame\(sessionRingTick\)/);
 assert.match(html,/id="session-countdown-ring"/);
 assert.match(html,/id="session-live-timer"/);
 assert.match(source[1],/session-live-timer'\)\.hidden=!complete&&!rest&&!!ex&&ex\.mode!=='min'/);
 assert.doesNotMatch(source[1],/elapsed%60/);
 assert.match(pulse,/#session-modal \.session-live-timer\[hidden\]\{display:none!important\}/);
 assert.match(html,/class="session-log-section"/);
 assert.match(html,/id="session-set-log"/);
 assert.match(source[1],/data-log-actual/);
 assert.match(pulse,/#session-modal #session-set-log \.set-log-item/);
 assert.doesNotMatch(pulse,/#session-modal\.pulse-flow-v58\.show:not\(\.session-overview-mode\) #session-controls\{position:fixed!important/);
 assert.doesNotMatch(pulse,/padding-bottom:calc\(145px \+ env\(safe-area-inset-bottom\)\)/);
 assert.match(pulse,/#session-modal\.pulse-flow-v58\.show:not\(\.session-overview-mode\) #session-controls\s*\{[\s\S]*?margin-top:5px/);
 assert.match(pulse,/@media\(max-width:740px\)\{/);
 assert.match(html,/id="session-ring-progress"/);
 assert.match(html,/id="session-ring-marker"/);
 assert.doesNotMatch(html,/id="session-cardio-countdown"/);
 assert.match(pulse,/@media\(max-width:740px\)/);
 assert.match(pulse,/@media\(prefers-reduced-motion:reduce\)/);
 assert.match(html,/<section id="zen-session" class="mode-screen zen-workout"/);
 assert.match(source[1],/function nextZen\(\)/);
 assert.match(source[1],/function selectZenStep\(index\)/);
 assert.match(html,/id="zen-step-arc"/);
 assert.match(html,/id="zen-step-marker"/);
 assert.match(html,/id="zen-total-time"/);
 assert.match(html,/id="zen-total-progress" role="progressbar"/);
 assert.match(css,/\.zen-workout \.zen-step-arc\{/);
 assert.match(css,/\.zen-workout \.zen-total-time\{/);
 assert.match(source[1],/stepCircle\.style\.strokeDashoffset|arc\.style\.strokeDashoffset/);
 assert.match(source[1],/zen-total-progress'\)\.setAttribute\('aria-valuenow'/);
 assert.match(source[1],/function startZenTimer\(\)/);
 assert.match(source[1],/zenTimer=setInterval\(function\(\)\{[\s\S]*?\},30\)/);
 assert.match(source[1],/function stopZenTimer\(\)/);
 assert.doesNotMatch(source[1],/zenAnimationTick|zenAnimationFrame|if\(activeZen\)zenTick\(\)/);
 assert.match(source[1],/med\?'STEG KVAR':'RÖRELSE KVAR'/);
 assert.match(css,/--mode-glow:/);
 assert.match(css,/drop-shadow\(0 0 8px var\(--mode-accent\)\)/);
 assert.match(css,/\.zen-clock-inner\{[^\n]*width:72%;max-width:72%/);
 assert.doesNotMatch(css,/stroke-dashoffset \.38s/);
 assert.doesNotMatch(css,/\.zen-clock-wrap\.is-switching/);
 assert.doesNotMatch(html,/firebase-app-compat|firebase-sync\.js|auth-gate\.js/);
});
